language: ruby
rvm:
  - 2.6.5

services:
  - postgresql

before_script:
  - psql -c 'create database chatfuel_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_success:
  - coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
