version: '3'

volumes:
  db:
  node_modules:
  bundle:

services:
  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    tmpfs: /app/tmp
    depends_on:
      - db
      - redis
    env_file: docker-env
    environment:
      - LANG=C.UTF-8
      - DATABASE_URL=postgres://postgres@CHANGEME/outbreak_mapping
      - RAILS_SERVE_STATIC_FILES=true
      - VIRTUAL_HOST=owso-stg.ilabsea.org
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=owso-stg.ilabsea.org
      - LETSENCRYPT_EMAIL=kakada@instedd.org
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  redis:
    image: redis:5.0.7

  
