version: '3'

volumes:
  bundle:
  db:

services:
  db:
    image: postgres:12.0
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: UPDATE_ME

  # nginx:
  #   restart: unless-stopped
  #   image: nginx:1.17.7
  #   volumes:
  #     - ./nginx/:/etc/nginx/conf.d/
  #     - ./certs/:/etc/nginx/certs/
  #   depends_on:
  #     - app
  #   ports:
  #     - 80:80
  #     - 443:443

  app: &rails
    image: ilabsea/chatfuel:0.1
    restart: unless-stopped
    volumes:
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
      - redis
    environment:
      - LANG=C.UTF-8
      - DATABASE_URL=postgres://postgres:UPDATE_ME@db/chatfuel_production
      - REDIS_URL=redis://redis:6379
      - RAILS_MAX_THREADS=15
      - PIDFILE=tmp/server.pid
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MASTER_KEY=UPDATE_ME
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
    ports:
      - 80:80
    command:
      - /bin/sh
      - -c
      - bundle exec puma -e production -b tcp://0.0.0.0:80

  redis:
    image: redis:5.0.7

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

