version: '3'

volumes:
  db:
  node_modules:
  bundle:
  # nginx-certs:
  # nginx-dhparam:
  # nginx-vhost:
  # nginx-html:

services:
  db:
    image: postgres:11.6
    volumes:
      - db:/var/lib/postgresql/data

  app: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    tmpfs: /app/tmp
    depends_on:
      - db
      - redis
    env_file: docker-env
    environment:
      - LANG=C.UTF-8
      - RAILS_SERVE_STATIC_FILES=true
      - VIRTUAL_HOST=owso-stg.ilabsea.org
      - VIRTUAL_PORT=3000
      - FB_PAGE_ID=105474597800095
      - FB_ACCESS_TOKEN=EAACnHokzay4BAIz5V7iw6nz7uyZCtk3XbdrM6dbcNyZA4W8kd4919w7HeZCp9JMwTTdaaUTZCtZCMLj3ubNWrx5ZAmfikCwUZClwsz0t1f6F7SP78qfBIlXzOmnBqFoXkPXV2gsogJfPguMXGU5TQfEXumohvqiREb6HgtZAh612vgZDZD
      - LETSENCRYPT_HOST=owso-stg.ilabsea.org
      - LETSENCRYPT_EMAIL=kakada@instedd.org
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  redis:
    image: redis:5.0.7

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - nginx-certs:/etc/nginx/certs:ro
  #     - nginx-dhparam:/etc/nginx/dhparam
  #     - nginx-vhost:/etc/nginx/vhost.d
  #     - nginx-html:/usr/share/nginx/html
  #   labels:
  #     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  #   depends_on:
  #     - app

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   depends_on:
  #     - nginx-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - nginx-certs:/etc/nginx/certs:rw
  #     - nginx-dhparam:/etc/nginx/dhparam
  #     - nginx-vhost:/etc/nginx/vhost.d
  #     - nginx-html:/usr/share/nginx/html
