version: '3'

volumes:
  db:
  rdb:
  nginx-certs:
  nginx-dhparam:
  nginx-vhost:
  nginx-html:

services:
  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbpass

  web: &rails
    image: radinreth/chatfuel:0.0.1
    restart: unless-stopped
    volumes:
      - /tmp/pids:/app/tmp/pids
    depends_on:
      - db
      - redis
    environment:
      - LANG=C.UTF-8
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=postgres://postgres:123456@db/chatfuel
      - VIRTUAL_HOST=owso-stg.ilabsea.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=owso-stg.ilabsea.org
      - LETSENCRYPT_EMAIL=radin@instedd.org
      - REDIS_URL=redis://redis:6379
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
    command:
    - /bin/sh
    - -c
    - bundle exec puma --preload -e production -b tcp://0.0.0.0:80
    
  redis:
    image: redis:5.0.7
    volumes:
      - rdb:/data

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq
    ports: []

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    depends_on:
      - web

    letsencrypt:
     image: jrcs/letsencrypt-nginx-proxy-companion
     depends_on:
       - nginx-proxy
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - nginx-certs:/etc/nginx/certs:rw
       - nginx-dhparam:/etc/nginx/dhparam
       - nginx-vhost:/etc/nginx/vhost.d
       - nginx-html:/usr/share/nginx/html
