FROM ruby:2.6-bullseye

RUN apt-get update -qq && apt-get install -y \
  nodejs npm \
  python2 \
  make \
  g++ \
  vim postgresql-client \
  && ln -s /usr/bin/python2 /usr/bin/python \
  && npm install -g yarn \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY Gemfile* package.json yarn.lock /app/

RUN gem install bundler -v 2.1.4 && \
  bundle install --jobs 20

COPY . /app

# Create symlink fonts
RUN ln -s /app/vendor/assets/fonts /usr/share/fonts
