:dynamic: true
:schedule:
  completed_ticket:
    cron: ['* * * * *', first_in: '0s']
    class: NotifyCompletedTicketJob
    description: "For tickets that are completed will be notified by messenger"
  quota:
    cron: '0 0,12 * * *'
    class: QuotaJob
    description: "Quota to broadcasting message to messenger users each day"
