:dynamic: true
:schedule:
  completed_ticket:
    cron: ['* * * * *', first_in: '0s']
    class: NotifyCompletedTicketJob
    description: "For tickets that are completed will be notified by messenger"
  quota:
    cron: '0 0,12 * * *'
    class: QuotaJob
    description: "Quota to broadcasting message to messenger users each day"

  alert_daily_notification:
    cron: "0 8 * * *"
    class: AlertDailyNotificationJob

  alert_weekly_notification:
    cron: "0 8 * * 1"
    class: AlertWeeklyNotificationJob